version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: drawing_platform_db
    restart: always
    environment:
      POSTGRES_USER: Danik
      POSTGRES_PASSWORD: Daniililiza9
      POSTGRES_DB: drawing_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: